// Module - BUILDER
export const PIZZA_BUILDER_STATE_CREATE = "PIZZA_BUILDER_STATE_CREATE";

export const PIZZA_BUILDER_SET = "PIZZA_SET";
export const PIZZA_BUILDER_UPDATE = "PIZZA_UPDATE";

export const PIZZA_BUILDER_NAME_SET = "PIZZA_NAME_SET";
export const PIZZA_BUILDER_NAME_UPDATE = "PIZZA_NAME_UPDATE";

// Module - CART
export const MISC_LIST_SET = "MISC_LIST_SET";

export const PIZZA_LIST_SET = "PIZZA_LIST_SET";
export const PIZZA_LIST_ADD = "PIZZA_LIST_ADD";
export const PIZZA_LIST_UPDATE = "PIZZA_LIST_UPDATE";
export const PIZZA_LIST_COUNT_UPDATE = "PIZZA_LIST_COUNT_UPDATE";

export const MISC_LIST_COUNT_UPDATE = "MISC_LIST_COUNT_UPDATE";
export const CURRENT_PHONE_SET = "CURRENT_PHONE_SET";
export const CURRENT_PHONE_UPDATE = "CURRENT_PHONE_UPDATE";
export const CURRENT_ADRESS_SET = "CURRENT_ADRESS_SET";
export const CURRENT_ADRESS_UPDATE = "CURRENT_ADRESS_UPDATE";

// Module - AUTH
export const USER_SET = "USER_SET";
export const USER_AUTHORIZED = "USER_AUTHORIZED";
export const USER_CLEAR_TEMP_PHONE = "USER_CLEAR_TEMP_PHONE";

// Module - ORDERS
export const ORDER_LIST_ADD = "ORDER_LIST_ADD";
